name: build-site
on: [push]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      
      # Clone the source code on the runner
      - uses: actions/checkout@v3
      
      # Perform setup for Ruby 2.7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          rubygems: latest
          bundler-cache: true
      
      # Build the Jekyll site
      - run: bundle exec jekyll build
      
      # Upload the built files to GitHub Pages
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "_site"
  
  # Deploy to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
